main:
  - identifier: produkte
    name: Produkte
    url: /produkte
    weight: 2
    parent: 
  - identifier: rss
    name: RSS
    url: /rss
    weight: 3
  - identifier: contact
    name: Kontakt
    url: /contact
    weight: 4
  - identifier: privacy
    name: Datenschutz
    url: /privacy
    weight: 5
  - identifier: terms
    name: AGB's
    url: /terms
    weight: 6
  - identifier: credits
    name: Impressum
    url: /credits
    weight: 7     
  - identifier: about
    name: Über uns
    url: /about  
    weight: 8
  - identifier: test
    name: Test Ecke(developer)
    url: /test
    weight: 200
  - identifier: eclectic
    name: Eclectic Theme
    url: /eclectic
    weight: 100
    parent: test
  - identifier: ionuts
    name: IO.Nuts
    url: /produkte/ionuts
    weight: 100
    parent: produkte
  - identifier: base
    name: Base
    url: /produkte/base
    weight: 200
    parent: produkte
  - identifier: flexiot
    name: Flex IoT
    url: /produkte/flexiot
    weight: 300
    parent: produkte  
  - identifier: rasppi
    name: Raspberry Pi
    url: /produkte/rasppi
    weight: 400
    parent: produkte
  - identifier: bluetooth
    name: Bluetooth Lösungen
    url: /produkte/bluetooth
    weight: 500
    parent: produkte       
  - identifier: beacon
    name: Beacon Netzwerke
    url: /produkte/beacon
    weight: 600
    parent: produkte
  - identifier: measure2go
    name: Measure2go
    url: /produkte/sensornetwork/measure2go
    weight: 700
    parent: produkte 
  - identifier: edgeantenna
    name: Edge Antennen
    url: /produkte/sensornetwork/edgeantenna
    weight: 800
    parent: produkte              