# alle infos zu der farbe http://html-color.org/de/e20074
color: "#e20074" # Farbschema "Razzmatazz"
copyright: "Copyright &copy; 2022 Taskit."
# Hinzufügen einer Formspree-ID
FormspreeCommentForm: mknykzqr
NetlifyCommentForm: 
