# 
#
#
#Hinzufügen von Parametern zum Abrufen verwandter Seiten
#
#
#

# equires a page to have a minimum score of 10 points for Hugo to list it as a related page (higher is better)
threshold: 10 
# Allows Hugo to use the pages created after the supplied page to find related pages
includeNewer: true

indices:
# Matches the tags from the front matter to create the score
- name: tags 
# Each matching tag is 10 points.
  weight: 10
# Gives scores to pages matching the date pattern
- name: date
  weight: 1
  # Pages in the same calendar year get 1 point.
  pattern: 2006